### ISSUE TITLE
breaks georgringer/news

### ISSUE THREAD

**Issue by t3pwa** [philip-hartmann/typo3fluid-api#1]
While having philip-hartmann/typo3fluid-api:0.2.0 installed and georgringer/news:11.4.1 on TYPO3 11.5.36 a exception occurs on the frontend end on pages with a news plugin. Uninstalling the api and the news are shown as expected.

(1/1) #1316104317 TYPO3\CMS\Extbase\Mvc\Exception

The default controller for extension "News" and plugin "NewsDetail" can not be determined. Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php.

Explanation: https://docs.typo3.org/typo3cms/exceptions/main/en-us/Exceptions/1316104317.html

It seems that somehow the middleware conflicts with news. I tried loading it later, without any success. Maybe related: https://forge.typo3.org/issues/99957

**Comment by philip-hartmann** [comment]
The linked issue is indeed related. We use TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface to access the configured template paths. Any use of extbase in a middleware seems to influence the TSFE cache.

**Comment by philip-hartmann** [comment]
@t3pwa I've released version 0.2.1 which fixes the problem.
